
services:
  gateway:
    build: ./gateway
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT}:8000"
    depends_on:
      - user_service


  user_service:
    build: ./user_service
    env_file:
      - .env
    ports:
      - "${USER_SERVICE_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql://${PSQL_USER}:${PSQL_PASSWORD}@db:5432/${USER_DB}
    depends_on:
      - db



  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "${PSQL_PORT}:5432"
    volumes:
      - user_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}


  redis:
    image: redis:alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  redis_commander:
    image: rediscommander/redis-commander
    restart: always
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  user_data:
  redis_data:
